### ISSUE TITLE
Publish linux binaries in releases

### ISSUE THREAD

**Issue by corneliusroemer** [citiususc/veryfasttree#13]
Linux binaries should be available through conda, but is there a reason you don't also publish them as release artefacts? Right now, it (wrongly) looks like you only support windows, when in fact you seem to support linux and windows.

**Comment by cesarpomar** [comment]
Hi,

Linux binaries are typically not as portable as Windows binaries due to differences in system libraries. While it is possible to make Linux binaries available through conda, publishing them as release artifacts may not be ideal because they might not work on all Linux distributions due to library version mismatches. For example, a binary compiled with one version of the C library (libc) may not work on another distribution with a different version of libc. 

However, if you have any suggestions on where else to publish the binaries, they are welcome. We are currently working on making them available on Debian and its derivatives through apt.

Best,
César

**Comment by corneliusroemer** [comment]
Thanks for the response, makes sense that you don't add binaries if you link dynamically. If you wanted to publish binaries, you could statically link.

**Comment by cesarpomar** [comment]
The compilation is done statically whenever possible, which includes third-party libraries hosted in the "lib" folder. However, using system libraries like libc or libgomp is generally not considered good practice and can result in certain issues.

For example, when distributing Linux binaries, they are often packaged as .deb packages. This allows the distribution to manage dependencies effectively.

**Comment by cesarpomar** [comment]
Currently, VeryFastTree is already available in the official Debian repository and its derivatives like Ubuntu. `apt install VeryFastTree`
Other distributions can make use of Bioconda, both through Conda `conda install -c bioconda veryfasttree` or by using Docker containers generated for their applications ` docker run quay.io/biocontainers/veryfasttree:<tag> <args>`.
