### ISSUE TITLE
Memory requirements compare to FastTree 2

### ISSUE THREAD

**Issue by dparks1134** [citiususc/veryfasttree#6]
Hi,

How do the memory requirements of Very Fast Tree compare to FastTree 2? Do any of the Very Fast Tree specific arguments impact requirement memory usage. Our typical use case is inferring a tree from a MSA with ~50,000 taxa and a length of ~5,000. Memory usage is often the rate limiting step for us as it restricts the number of trees we can infer at the same time.

Thanks,
Donovan

**Comment by cesarpomar** [comment]
Hi,
Veryfasttree is implemented in C++, so you can expect an overhead due to the use of objects. For example, in Fasttree, each sequence line in input file was an char * (8 bytes pointer + sequence length) and in very fasttree a std::string (24 bytes object + sequence length). If there are many sequences with little length, the overhead will be more noticeable.

In addition, increasing the number of threads increases memory usage due to the creation of structures to store intermediate work in parallel. As well as the vector extensions that require padding per sequence to align the structures when using avx256 with floats or avx512.

If you have any other questions please contact me

**Comment by jcpichel** [comment]
You can find in the Supplementary Material of the VeryFastTree paper [(PDF)](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformatics/36/17/10.1093_bioinformatics_btaa582/8/btaa582_supplementary_material.pdf?Expires=1608321115&Signature=cZoR11YMcPikku2zFO88H5Elt-cGa3bpqLrybEAQsydQFUQCXcu0xHiWs~UJ0L1icbTP3vMWpO4flhDaof3T9SIvWMlb2fd6CnKzHI~kMyUHg3jYimZmFVuKcaFNyvhd-DY53R7M3zDAUVypRju63bz1DfMASvmWmLgUei1QEHqzHfsOagfWc~7jWVUYDXwn4lI0A8j6I-a6woXO1kjGr7AOAXoeLcSfD2vjhci0wfEYoHD4GBzU~mN1KA79q7q1J~z~oXhEoBnf0uOTkki0pLffoSlBxssmm0YgUmSg7NCTAmY55-itJlaowXqjREI6j6TZxCfulLv0FZUiG-oRjA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA) some numbers about the memory consumption in comparison to FastTree.
