### ISSUE TITLE
VeryFastTree memory use seems to be 3x FastTree

### ISSUE THREAD

**Issue by rmcolq** [citiususc/veryfasttree#8]
I've been running VeryFastTree on large subsets of SARS-CoV-2 genomes and keep running out of memory. I expect to be able to build an 80k tip tree with 45GB RAM and a 110k tip tree with 60GB RAM with FastTree2 (3 threads) but they take forever. I initially tried giving VeryFastTree just a bit more based on resource plots in your supplementary materials, but found that with my dataset a 70k tip tree uses more than 100GB RAM (8 threads). Does this match up with your expectation of how the memory requirements should compare?

**Comment by cesarpomar** [comment]
Hi,

The main memory differences between fastree2 and VeryFastTree are neigong joining parallel processing, C vs C++ and AVX extensions.  As fastree2 documentation explain: “During neighbor joining, FastTree stores profiles of internal nodes instead of a distance matrix.” So, when you use 8 threads each thread stores this own profile increasing the memory overhead. 

Moreover, VeryFastTree was implemented in C++ to perform optimizations at runtime without recompiling and Objects have a cost. For example, alignment is a string and its cost is 24 bytes. If you have a dataset with alignments of 1000 characters, the overhead will be 24 / (24 + 1000) * 100 = 2.34%. On the other hand, if you have a large dataset of 50 characters alignments, the overhead will be 32%. 

Finally, if you use AVX 256 or AVX 512 instead of SEE, a padding is required in the computation arrays to make the number of proteins multiple of 8 or 16.

**Comment by rmcolq** [comment]
Thank you for this!
